stages:
  - test
  - build


test-backend:
  tags: 
    - java
  stage: test
  script:
    - ./gradlew :test
  
build-backend: 
  tags: 
    - java
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths: 
      - backend/build/**
    when: always
    expire_in: 2 hours
      
