stages:
  - build
  
build-backend: 
  tags: 
    - gradle
  stage: build
  script:
    - gradle clean install 
  artifacts:
    paths: 
      - backend/target/**
    when: always
    expire_in: 2 hours
      
