stages:
  - build
  - test
  
build-backend: 
  tags: gradle
  stage: build
  script:
    - .\gradlew clean install 
  artifacts:
    paths: 
      - backend/target/**
    when: always
    expire_in: 2 hours
      