stages:
  - test
  - build
  
test-backend:
  tags: 
    - gradle
  stage: test
  script:
   - git clone https://git.thm.de/webservices-2020/aws-docker-orchestration ado
    - cd ado
    - ./docker-compose build
    - ./docker-compose up &
    - cd ..
    - ./gradlew test -info
  
build-backend: 
  tags: 
    - gradle
  stage: build
  script:
    - git clone https://git.thm.de/webservices-2020/aws-docker-orchestration ado
    - cd ado
    - ./docker-compose build
    - ./docker-compose up &
    - cd ..
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths: 
      - backend/build/**
    when: always
    expire_in: 2 hours
      
