stages:
  - build
  - test

test-backend: 
  tags: 
    - java
  stage: test
  script:
    - ./gradlew test 
  
build-backend: 
  tags: 
    - java
  stage: build
  script:
    - ./gradlew clean install 
  artifacts:
    paths: 
      - backend/target/**
    when: always
    expire_in: 2 hours
      
