stages:
  - test
  - build
  
test-backend:
  tags: 
    - gradle
  stage: test
  before_script
    - apt install docker
    - curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - git clone https://$ISSUE_REPO_USERNAME:$ISSUE_REPO_TOKEN@git.thm.de/webservices-2020/aws-docker-orchestration ado 
    - cd ado
    - ls
    - docker-compose build
    - docker-compose up &
    - cd ..
    - ./gradlew test -info
  
build-backend: 
  tags: 
    - gradl
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths: 
      - backend/build/**
    when: always
    expire_in: 2 hours
      
